/**
 * `/llms.txt` endpoint.
 *
 * Generated by src/lib/llms.ts from the same collections that render the
 * site, so the index can never list pages that do not exist (or omit
 * pages that do). Served as plain text; the URL is base-aware
 * (`<base>/llms.txt` under a repository-subpath deployment).
 */
import type { APIRoute } from "astro";
import { buildLlmsTxt } from "../lib/llms";

export const GET: APIRoute = async () => {
  const body = await buildLlmsTxt();
  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
